### ISSUE TITLE
How to get Win num status in other statusline?

### ISSUE THREAD

**Issue by lkhphuc** [nikvdp/neomux#11]
I'm currently using galaxyline and the window status doesn't appear out of the box? How can I retrieve the num window so I can configure it myself. Thanks.

**Comment by nikvdp** [comment]
Hey @lkhphuc good to hear from you! Neomux exposes a `WindowNumber()` function that you can use for this.

There's an example of how I use it with galaxyline [here](https://github.com/nikvdp/nvim-lsp-config/blob/master/lua/statusbar.lua#L185-L199) that may be helpful. With galaxyline you'll probably also want to add it to `short_line_right` in order to have the win number show for both focused and unfocused windows ([example](https://github.com/nikvdp/nvim-lsp-config/blob/master/lua/statusbar.lua#L226))
