### ISSUE TITLE
how to reproduce compiled Python executables stored in plugin/Linux.x86_64.bin and https://github.com/nikvdp/neomux/tree/master/plugin/Darwin.x86_64.bin

### ISSUE THREAD

**Issue by matu3ba** [nikvdp/neomux#18]
The binaries itself are also huge and I dont understand, why you dont want to commit the source files into this repo for others to hack on.

**Comment by nikvdp** [comment]
They are committed into this repo, if you'd like to hack on them feel free! You can reproduce them by running [plugin/scripts/build-nvr.sh](https://github.com/nikvdp/neomux/blob/master/plugin/scripts/build-nvr.sh) in this repo (you'll need pyinstaller and the neovim-remote python package installed).

You don't need them, you can also just install neovim-remote yourself via pip as the README mentions. They're just there as a convenience so that the plugin works out of the box without forcing end users to install python or deal with python dependencies and virtualenv issues.

**Comment by nikvdp** [comment]
closing this for now, but feel free to re-open if you have more questions
